-- Insert Categories
INSERT INTO categories (name, description, created_at, updated_at) VALUES
('Shampoo', 'Shampoos para todo tipo de cabello', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Acondicionadores', 'Acondicionadores y cremas de enjuague', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Tratamientos', 'Tratamientos capilares intensivos', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Styling', 'Productos de peinado y acabado', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Color', 'Tintes y productos de coloración', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Herramientas', 'Herramientas y accesorios para el cabello', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Insert Products
INSERT INTO products (name, brand, price, image_url, rating, description, ingredients, how_to_use, stock, badges, category_id, created_at, updated_at) VALUES
('Shampoo Nutritivo con Argán', 'HairLux', 12500.00, 'https://images.unsplash.com/photo-1626094020000-111499777780?q=80&w=1974&auto=format&fit=crop', 4.5, 'Un shampoo enriquecido con aceite de argán que nutre profundamente el cabello, dejándolo suave, brillante y manejable. Ideal para cabellos secos y dañados.', 'Agua, Sodium Laureth Sulfate, Cocamidopropyl Betaine, Argania Spinosa Kernel Oil, Glycerin, Parfum.', 'Aplicar sobre el cabello mojado, masajear suavemente hasta crear espuma y enjuagar abundantemente. Repetir si es necesario.', 10, 'Nuevo,Vegano', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Acondicionador Reparador', 'EcoHair', 10800.00, 'https://images.unsplash.com/photo-1626094020000-111499777780?q=80&w=1974&auto=format&fit=crop', 4.2, 'Acondicionador formulado para reparar y fortalecer el cabello desde la raíz hasta las puntas. Reduce el quiebre y mejora la elasticidad.', 'Agua, Cetearyl Alcohol, Behentrimonium Chloride, Hydrolyzed Keratin, Panthenol, Parfum.', 'Después del shampoo, aplicar de medios a puntas, dejar actuar 2-3 minutos y enjuagar bien.', 15, 'Oferta', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Mascarilla Hidratante Profunda', 'GlowHair', 18900.00, 'https://images.unsplash.com/photo-1626094020000-111499777780?q=80&w=1974&auto=format&fit=crop', 4.8, 'Mascarilla de hidratación profunda que restaura la vitalidad del cabello. Perfecta para tratamientos semanales.', 'Agua, Cetearyl Alcohol, Glycerin, Shea Butter, Keratin, Panthenol, Parfum.', 'Aplicar sobre cabello limpio y húmedo, dejar actuar 10-15 minutos y enjuagar abundantemente.', 8, '', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Serum Anti-Frizz con Keratina', 'SilkyStrands', 15000.00, 'https://images.unsplash.com/photo-1626094020000-111499777780?q=80&w=1974&auto=format&fit=crop', 4.6, 'Serum ligero que controla el frizz y aporta brillo. Enriquecido con keratina para fortalecer el cabello.', 'Cyclopentasiloxane, Dimethicone, Hydrolyzed Keratin, Argan Oil, Vitamin E, Parfum.', 'Aplicar una pequeña cantidad sobre cabello húmedo o seco, de medios a puntas. No enjuagar.', 20, 'Top Ventas', 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Aceite de Argán Puro', 'Nature''s Best', 9500.00, 'https://images.unsplash.com/photo-1626094020000-111499777780?q=80&w=1974&auto=format&fit=crop', 4.7, 'Aceite de argán 100% puro y orgánico para nutrir e hidratar el cabello. Multiuso.', '100% Argania Spinosa Kernel Oil.', 'Aplicar unas gotas sobre el cabello o añadir a mascarillas. También puede usarse en piel y uñas.', 12, 'Orgánico', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Spray Protector Térmico', 'HeatGuard', 8200.00, 'https://images.unsplash.com/photo-1626094020000-111499777780?q=80&w=1974&auto=format&fit=crop', 4.3, 'Protege el cabello del daño causado por herramientas de calor hasta 230°C. Fórmula ligera que no deja residuos.', 'Agua, PVP, Panthenol, Glycerin, Cyclomethicone, Parfum.', 'Vaporizar sobre el cabello antes de usar secador, plancha o rizador. Mantener a 20cm de distancia.', 18, '', 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Tinte Permanente Castaño', 'VividColor', 11000.00, 'https://images.unsplash.com/photo-1626094020000-111499777780?q=80&w=1974&auto=format&fit=crop', 4.0, 'Tinte permanente de coloración profesional. Cobertura total de canas con acabado brillante.', 'Aqua, Cetearyl Alcohol, Ammonia, Ethanolamine, Colorantes (CI 77491, CI 77492, CI 77499).', 'Mezclar con revelador según instrucciones. Aplicar sobre cabello seco, dejar actuar 30-40 minutos y enjuagar.', 5, 'Nuevo', 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cepillo Desenredante', 'SmoothBrush', 6000.00, 'https://images.unsplash.com/photo-1626094020000-111499777780?q=80&w=1974&auto=format&fit=crop', 4.9, 'Cepillo con cerdas flexibles que desenreda sin dolor ni daño. Ideal para todo tipo de cabello.', 'N/A - Producto físico (cerdas de nylon, mango ergonómico).', 'Cepillar suavemente desde las puntas hacia la raíz. Usar sobre cabello húmedo o seco.', 25, '', 6, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);


